{
    'name': 'Cabal Contract Management',
    'author': 'Redes Litorales SA de CV',
        "version": "17.0.8.1.25",
    'category': 'Sales Management',
    'sequence': -100,
    'summary': 'Contract Management',
    'description': """contract_management""",
    'depends': ['base', 'account', 'contacts', 'sale', 'crm', 'odoo_docusign', 'portal'],
    'data': [
        'security/contract_management_security.xml',
        'security/ir.model.access.csv',
        'data/dashboard_data.xml',
        'data/contract_expiration_cron.xml',
        'data/contract_renewal_cron.xml',
        'data/cm_renewals_pipeline.xml',
        'views/view_contract_clause.xml',
        'views/contract_addendum_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_next_invoice_date_view.xml',
        'views/sale_order_readonly_fields.xml',
        'views/sale_subscription_button_visibility.xml',
        'views/sale_cover_letter_views.xml',
        'views/sale_terms_conditions_view.xml',
        'views/subscription_closure_form.xml',
        'views/subscription_closure_wizard_view.xml',
        'views/subscritpion_problems_form.xml',
        'views/subscription_competitor_form.xml',
        'views/view_sale_order_sub_close_form.xml',
        'views/pause_subscription_wizard_view.xml',
        'views/pause_subscription_wizard_action.xml',
        'views/reactivate_subscription_wizard_view.xml',
        'views/reactivate_subscription_wizard_action.xml',
        'views/contract_termination_wizard_view.xml',
        'views/view_contract_management_views.xml',
        'views/contract_management_actions.xml',
        'views/view_contract_management_term_form.xml',
        'views/view_docusign_connector.xml',
        'views/contract_dashboard_views.xml',
        'reports/customer_contract_action.xml',
        'views/contract_send_method_wizard_view.xml',
        'views/contract_transfer_wizard_view.xml',
        'views/contract_transfer_wizard_action.xml',
        'reports/report_modify_quote.xml',        
        'reports/report_contract_template.xml',
        'reports/report_contract_addendum.xml',      
        'views/contract_management_menus.xml',
        'views/suspended_subscription_views.xml',
        'views/res_users_views.xml',
        'views/res_config_settings_views.xml',
        'views/portal_contract_templates.xml',
    ],
    'demo': [],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}