{
    'name': 'Cabal Contract Management',
    'author': 'Redes Litorales SA de CV',
    "version": "17.0.1.1.0",
    'category': 'Sales Management',
    'sequence': -100,
    'summary': 'Contract Management',
    'description': """contract_management""",
    'depends': ['base', 'account', 'contacts', 'sale', 'odoo_docusign'],
    'data': [
        'views/view_contract_clause.xml',
        'views/sale_order_views.xml',
        'views/sale_cover_letter_views.xml',
        'views/sale_terms_conditions_view.xml',
        'views/subscription_closure_form.xml',
        'views/subscription_closure_wizard_view.xml',
        'views/subscritpion_problems_form.xml',
        'views/subscription_competitor_form.xml',
        'views/view_sale_order_sub_close_form.xml',
        'views/pause_subscription_wizard_view.xml',
        'views/pause_subscription_wizard_action.xml',
        'views/reactivate_subscription_wizard_view.xml',
        'views/reactivate_subscription_wizard_action.xml',
        'views/view_contract_management_views.xml',
        'views/contract_management_actions.xml',
        'views/view_contract_management_term_form.xml',
        'views/view_sale_order_sub_close_form.xml',        
        'views/view_docusign_connector.xml',
        'reports/customer_contract_action.xml',
        'views/view_product_category.xml',
        'views/contract_send_method_wizard_view.xml',
        'views/contract_transfer_wizard_view.xml',
        'views/contract_transfer_wizard_action.xml',
        'reports/report_modify_quote.xml',        
        'reports/report_contract_template.xml',        
        'views/contract_management_menus.xml',
        'views/res_users_views.xml',
        'security/contract_management_security.xml',
        'security/ir.model.access.csv',
    ],
    'demo': [],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}