{
    'name': 'Cabal Contract Management',
    'author': 'Bálsamo Labs SAS',
    'maintainer': 'Bálsamo Labs SAS',
    'version': '17.0.8.6.36',
    'category': 'Sales Management',
    'sequence': -100,
    'summary': 'Contract Management',
    'description': """contract_management""",
    'depends': [
        'base',
        'dte_base',
        'account',
        'electronic_invoicing',
        'contacts',
        'sale',
        'crm',
        'odoo_docusign',
        'portal',
        'customer_status',
        'printnode_base',
        'helpdesk',
    ],
    'data': [
        'security/contract_management_security.xml',
        'security/ir.model.access.csv',
        'data/contract_litigation_data.xml',
        'data/contract_litigation_mail_templates.xml',
        'data/dashboard_data.xml',
        'data/contract_expiration_cron.xml',
        'data/contract_renewal_cron.xml',
        'data/contract_auto_renew_cron.xml',
        'data/email_domain_fix_cron.xml',
        'data/suspended_reservation_cron.xml',
        'data/customer_status_cron.xml',
        'data/cm_renewals_pipeline.xml',
        'data/mail_templates.xml',
        'views/view_contract_clause.xml',
        'views/contract_addendum_views.xml',
        'views/sale_order_views.xml',
        'views/sale_order_next_invoice_date_view.xml',
        'views/sale_order_readonly_fields.xml',
        'views/sale_subscription_button_visibility.xml',
        'views/sale_cover_letter_views.xml',
        'views/sale_terms_conditions_view.xml',
        'views/subscription_closure_form.xml',
        'views/subscription_closure_wizard_view.xml',
        'views/subscritpion_problems_form.xml',
        'views/subscription_competitor_form.xml',
        'views/view_sale_order_sub_close_form.xml',
        'views/pause_subscription_wizard_view.xml',
        'views/pause_subscription_wizard_action.xml',
        'views/change_payment_date_wizard_view.xml',
        'views/change_payment_date_wizard_action.xml',
        'views/change_payment_date_batch_wizard_view.xml',
        'views/res_partner_payment_date_batch_view.xml',
        'views/res_partner_email_verify_banner.xml',
        'views/customer_account_statement_views.xml',
        'views/reactivate_subscription_wizard_view.xml',
        'views/reactivate_subscription_wizard_action.xml',
        'views/contract_termination_wizard_view.xml',
        'views/view_contract_management_views.xml',
        'views/contract_management_actions.xml',
        'views/view_contract_management_term_form.xml',
        'views/view_docusign_connector.xml',
        'views/contract_dashboard_views.xml',
        'reports/customer_contract_action.xml',
        'views/contract_send_method_wizard_view.xml',
        'views/contract_resend_wizard_view.xml',
        'views/contract_transfer_wizard_view.xml',
        'views/contract_transfer_wizard_action.xml',
        'reports/report_modify_quote.xml',        
        'reports/report_contract_template.xml',
        'reports/report_contract_addendum.xml',      
        'reports/customer_account_statement_report.xml',
        'reports/contract_litigation_report.xml',
        'views/contract_management_menus.xml',
        'views/subscription_installation_fee_report_views.xml',
        'views/residential_iptv_report_views.xml',
        'views/suspended_subscription_views.xml',
        'views/contract_litigation_views.xml',
        'views/account_bad_debt_writeoff_views.xml',
        'views/res_users_views.xml',
        'views/res_config_settings_views.xml',
        'views/portal_contract_templates.xml',
    ],
    'demo': [],
    'assets': {
        'web.assets_backend': [
            'contract_management/static/src/scss/contract_dashboard.scss',
        ],
    },
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
}
